### PR TITLE
Updated the CDS structures - Using "OS == Win" key instead of "OFFLINE==True"

### PR DESCRIPTION
**Pull request by DStavilaNI**
Updated the CDS structures - instead of the "OFFLINE==True" key we are using the "OS === Win" one, to insure functionality only on the Windows targets. Previous implementation was buggy.

### CODE REVIEW

**Comment by eatondan** [comment]
@DStavilaNI The conditional structure has OS==Win in one case and OFFLINE == FALSE, Default in the other. Please remove the OFFLINE == FALSE in the cases the are looking at OS.

**Comment by eatondan** [comment]
@DStavilaNI  Please add a conditional disable around SysDef.Node.Info.Get.vi for consistency.

**Comment by DStavilaNI** [comment]
> 
> 
> @DStavilaNI The conditional structure has OS==Win in one case and OFFLINE == FALSE, Default in the other. Please remove the OFFLINE == FALSE in the cases the are looking at OS.

Done ... used "OS==RT" as default ... I think it would be a bit more understandable

**Comment by eatondan** [comment]
@DStavilaNI  Everything looks great! Please add a built version and I will merge the request.

**Comment by XenderMd** [comment]
> 
> 
> @DStavilaNI Everything looks great! Please add a built version and I will merge the request.

Done ;)

**Pull request merged**
